---
- hosts: ubuntu_landing
  vars:
    git_url: 'https://github.com/laravel/laravel.git'
    destdir: '/var/www/laravel'
    register: cloned
    username: 'admin'
    password: '123456'
    domain: 'lxc_landing.dev'
  roles:
   - php
   - lv
  
